version: "2"

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
  settings:
    govet:
      enable:
        - shadow

formatters:
  enable:
    - gofmt
    - goimports
